import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col`}>
        <SiteHeader />
        {children}
      </body>
    </html>
  );
}

function SiteHeader() {
  return (
    <nav className="px-6 py-4">
      <div className="mx-auto flex max-w-7xl items-center justify-between">
        <Link className="text-xl font-semibold" href="/">
          Gallery
        </Link>

        <Link href="/sign-in" className="text-sm">
          Sign In
        </Link>
      </div>
    </nav>
  );
}
